[project]
name = "mqtt2homekit"
version = "0.2.0"
license = "Apache-2.0"
description = "Transparently bridge an MQTT topic tree to HomeKit."
readme = "README.rst"
authors = [{ name = "Matthew Schinckel" },{name = "Michael Beck"}]
requires-python = ">=3.12"
dependencies = [
    "HAP-python[QRCode]>=5.0.0",
    "paho-mqtt>=2.1.0",
]

[project.optional-dependencies]
dev = [
    "pytest>=8.4.2",
    "pytest-mock>=3.15.1",
    "ruff>=0.14.0",
    "mypy>=1.18.2",
    "coverage>=7.10.7"
]

[tool.ruff.lint]
select = [
    "C",        #complexity
    "E",        #pycodestyle
    "F",        #Pyflakes
    "UP",       #pyupgrade
    "B",        #flake8-bugbear
    "SIM",      #flake8-simplify
    "I",        #isort
]

ignore = [
    "E501",     # line too long
]

[tool.ruff.format]
quote-style = "single"
indent-style = "tab"
docstring-code-format = true

[tool.ruff.lint.isort]
force-sort-within-sections = true
combine-as-imports = true
split-on-trailing-comma = false
