BAUD ?= 460800
FLASH_MODE ?= qio
START ?= 0x3c000

deploy:
	echo "Writing firmware to esp8266"
	esptool.py --port $(PORT) --baud $(BAUD) write_flash --flash_mode $(FLASH_MODE) --flash_size detect $(START) $(FILE)
